/**
 * Created by Administrator on 2017/3/27.
 */
export default{
  SET_INFO: 'SET_INFO',  //设置信息
  ADD_SHIPPING_INFO: 'ADD_SHIPPING_INFO',  //添加物流信息
  REMOVE_ONE_SHIPPING: 'REMOVE_ONE_SHIPPING', //移除单个物流
  REMOVE_ONE_COLLECTION: 'REMOVE_ONE_COLLECTION', //移出收藏夹
  CANCLE_ONE_ORDER: 'CANCLE_ONE_ORDER', //取消订单
  REMOVE_ONE_ORDER: 'REMOVE_ONE_ORDER', //移除订单
  COMMENT_ONE_ORDER: 'COMMENT_ONE_ORDER', //评价订单
  CONFIRM_RECEIVE_ONE_ORDER: 'CONFIRM_RECEIVE_ONE_ORDER', //确认收货订单
  ADD_ONE_SHOPCAR: 'ADD_ONE_SHOPCAR'  //加入购物车
}
